// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"nblog.org.cn/software_nblog_core/biz/middleware"
	"nblog.org.cn/software_nblog_core/conf"
	"nblog.org.cn/software_nblog_core/utils"
	"os"
)

func main() {
	f := redirectLogFile()
	defer f.Close()

	h := server.Default(
		server.WithHostPorts(conf.IP + ":" + conf.PORT),
	)
	h.Use(middleware.Cors(), middleware.HertzLogMw(), middleware.HertzErrCodeMw())
	register(h)
	h.Spin()
}

func redirectLogFile() *os.File {
	// 重定向日志文件
	logFile := "./logs/" + utils.GetToDay() + ".txt"
	f, err := os.OpenFile(logFile, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		hlog.Errorf("Failed to open error log file: %v", logFile)
		panic(err)
	}

	hlog.SetOutput(f)
	return f
}
